### ISSUE TITLE
bug: 1.20.1 无法启动游戏

### ISSUE THREAD

**Issue by NumberSir** [17TheWord/MC_QQ_Forge#13]
> 日志文件

[latest.log](https://github.com/17TheWord/MC_QQ_Forge/files/15309296/latest.log)

> 崩溃信息

[crash-2024-05-14_21.46.37-fml.txt](https://github.com/17TheWord/MC_QQ_Forge/files/15309313/crash-2024-05-14_21.46.37-fml.txt)

> 补充

使用的是官方 Forge 端，版本 47.2.19，模组是从 [@actions/15](https://github.com/17TheWord/MC_QQ_Forge/actions/runs/8717894792) 下载的

**Comment by 17TheWord** [comment]
已在 [🐛 Package right tool name (#14)](https://github.com/17TheWord/MC_QQ_Forge/actions/runs/9091252522) 修复，可以重试

**Comment by NumberSir** [comment]
正常启动了，感谢
